### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### guard/guard-livereload now has a Chat Room on Gitter

@jibiel has just created a chat room. You can visit it here: [https://gitter.im/guard/guard-livereload](https://gitter.im/guard/guard-livereload?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/guard/guard-livereload?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by jibiel** [comment]
@e2 Lol, should I merge that? Given that we can't guarantee any form of live support.

**Comment by e2** [comment]
It may be useful for debugging. 

And I find that issues expire quickly anyway. Issues are probably easier to Google though (because of the issue titles), so reporting issues first is probably the best way to go, anyway.

Probably better for people to join a chat than to add their full report details under existing ones. So if one user reports an issue, but then they "disappear" (they don't have time) and another user has the same issue - that next user can continue on Gitter (if they have time to work things out).

Maybe I should add to Troubleshooting information about searching already closed issues too?

**Comment by e2** [comment]
Also, guard-livereload is "complex", so being able to chat freely may help a lot.

**Comment by jibiel** [comment]
> Maybe I should add to Troubleshooting information about searching already closed issues too?

Yeah, properly formulated, this might cool things up for issue tracker a bit.
The Gitter room is also worth a mention. I think maybe `CONTRIBUTING.md` might be more proper for that.

**Pull request merged**
