### PR TITLE
Add `Troubleshooting` section to the README.md

### LINKED ISSUE #134: error: "hw.ncpu" is an unknown key
While running livereload through guard, I am getting the following errors:

12:23:49 - DEBUG - Command execution: hash stty
12:23:49 - DEBUG - Guard starts all plugins
12:23:49 - DEBUG - Hook :start_begin executed for Guard::Compass
12:23:49 - INFO - Guard::Compass is waiting to compile your stylesheets.
12:23:49 - DEBUG - Hook :start_end executed for Guard::Compass
12:23:49 - DEBUG - Hook :start_begin executed for Guard::LiveReload
RuntimeError: no acceptor (port is in use or requires root privileges) at /ruby/gems/gems/eventmachine-1.0.7/lib/eventmachine.rb:526:in `start_tcp_server'
[2015-03-16T12:23:49.939 DEBUG Guard::Ui(12511) #E19BB24975A2] Hook :start_end executed for Guard::LiveReload
error: "hw.ncpu" is an unknown key
12:23:50 - INFO - Guard is now watching at '/sites/al   l/themes/hqbars_omega'
12:23:50 - DEBUG - Start interactor
[1] guard(main)> exit
12:24:14 - DEBUG - Interactor was stopped or killed
12:24:14 - DEBUG - Guard stops all plugins
12:24:14 - DEBUG - Hook :stop_begin executed for Guard::Compass
12:24:14 - DEBUG - Hook :stop_end executed for Guard::Compass
12:24:14 - DEBUG - Hook :stop_begin executed for Guard::LiveReload
12:24:14 - DEBUG - Hook :stop_end executed for Guard::LiveReload
12:24:14 - INFO - Bye bye...

====

This is trying to guard an omega theme on Drupal 7. I am running on redhat linux (hosted by BlueHost)..

Would greatly appreciate any help i can get. 

Thanks!

### PR DESCRIPTION
**Pull request by jibiel**
Clarifies and resolves #134. Credit goes to @e2.

### CODE REVIEW

**Comment by e2** [comment]
I'd instead suggest people install Listen 3.x, which doesn't use Celluloid anymore. It should be faster and have less problems.

**Comment by e2** [comment]
I think the additional files watched (sass, scss, coffeescript) are not needed, because LiveReload should only reload when the output files have been created.

E.g. if you edit `foo.scss`, the output will be `foo.css` - and you don't want to tell the browser to reload until `foo.css` has been written to the hard drive.

So the only file LiveReload needs to know about are files the browser understands (css, images, html, js).

**Comment by jibiel** [comment]
@e2 @7847818 is from the other PR, #144. Sorry for the confusion.

Your words make perfect sense, but this doesn't seem the way thing's working now. The compiled assets  are not presented in the application directories. I had to explicitly specify those extensions in order for assets with the new naming convention to be reloaded. And I'm not the only one — #140.

**Comment by e2** [comment]
I've updated the Readme (I cherry-picked your comment then updated it) and the template has been reworked on master.

Open a new PR if something is still not working.

**Pull request closed without merging**
